/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmountRouteImport } from './routes/amount'
import { Route as RecipientRouteImport } from './routes/recipient'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SendRouteImport } from './routes/send'
import { Route as ApiCountriesRouteImport } from './routes/api/countries'
import { Route as ApiTransfersRouteImport } from './routes/api/transfers'
import { Route as SuccessIdRouteImport } from './routes/success.$id'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ApiExchangeRatesCurrencyRouteImport } from './routes/api/exchange-rates.$currency'
import { Route as ApiTransfersIdRouteImport } from './routes/api/transfers.$id'
import { Route as ApiTransfersIdStatusRouteImport } from './routes/api/transfers.$id.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmountRoute = AmountRouteImport.update({
  id: '/amount',
  path: '/amount',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientRoute = RecipientRouteImport.update({
  id: '/recipient',
  path: '/recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesRoute = ApiCountriesRouteImport.update({
  id: '/api/countries',
  path: '/api/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransfersRoute = ApiTransfersRouteImport.update({
  id: '/api/transfers',
  path: '/api/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessIdRoute = SuccessIdRouteImport.update({
  id: '/success/$id',
  path: '/success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRatesCurrencyRoute =
  ApiExchangeRatesCurrencyRouteImport.update({
    id: '/api/exchange-rates/$currency',
    path: '/api/exchange-rates/$currency',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransfersIdRoute = ApiTransfersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransfersRoute,
} as any)
const ApiTransfersIdStatusRoute = ApiTransfersIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiTransfersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amount': typeof AmountRoute
  '/recipient': typeof RecipientRoute
  '/review': typeof ReviewRoute
  '/send': typeof SendRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/transfers': typeof ApiTransfersRouteWithChildren
  '/success/$id': typeof SuccessIdRoute
  '/track/$id': typeof TrackIdRoute
  '/track/': typeof TrackIndexRoute
  '/api/exchange-rates/$currency': typeof ApiExchangeRatesCurrencyRoute
  '/api/transfers/$id': typeof ApiTransfersIdRouteWithChildren
  '/api/transfers/$id/status': typeof ApiTransfersIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amount': typeof AmountRoute
  '/recipient': typeof RecipientRoute
  '/review': typeof ReviewRoute
  '/send': typeof SendRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/transfers': typeof ApiTransfersRouteWithChildren
  '/success/$id': typeof SuccessIdRoute
  '/track/$id': typeof TrackIdRoute
  '/track': typeof TrackIndexRoute
  '/api/exchange-rates/$currency': typeof ApiExchangeRatesCurrencyRoute
  '/api/transfers/$id': typeof ApiTransfersIdRouteWithChildren
  '/api/transfers/$id/status': typeof ApiTransfersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amount': typeof AmountRoute
  '/recipient': typeof RecipientRoute
  '/review': typeof ReviewRoute
  '/send': typeof SendRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/transfers': typeof ApiTransfersRouteWithChildren
  '/success/$id': typeof SuccessIdRoute
  '/track/$id': typeof TrackIdRoute
  '/track/': typeof TrackIndexRoute
  '/api/exchange-rates/$currency': typeof ApiExchangeRatesCurrencyRoute
  '/api/transfers/$id': typeof ApiTransfersIdRouteWithChildren
  '/api/transfers/$id/status': typeof ApiTransfersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amount'
    | '/recipient'
    | '/review'
    | '/send'
    | '/api/countries'
    | '/api/transfers'
    | '/success/$id'
    | '/track/$id'
    | '/track/'
    | '/api/exchange-rates/$currency'
    | '/api/transfers/$id'
    | '/api/transfers/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amount'
    | '/recipient'
    | '/review'
    | '/send'
    | '/api/countries'
    | '/api/transfers'
    | '/success/$id'
    | '/track/$id'
    | '/track'
    | '/api/exchange-rates/$currency'
    | '/api/transfers/$id'
    | '/api/transfers/$id/status'
  id:
    | '__root__'
    | '/'
    | '/amount'
    | '/recipient'
    | '/review'
    | '/send'
    | '/api/countries'
    | '/api/transfers'
    | '/success/$id'
    | '/track/$id'
    | '/track/'
    | '/api/exchange-rates/$currency'
    | '/api/transfers/$id'
    | '/api/transfers/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmountRoute: typeof AmountRoute
  RecipientRoute: typeof RecipientRoute
  ReviewRoute: typeof ReviewRoute
  SendRoute: typeof SendRoute
  ApiCountriesRoute: typeof ApiCountriesRoute
  ApiTransfersRoute: typeof ApiTransfersRouteWithChildren
  SuccessIdRoute: typeof SuccessIdRoute
  TrackIdRoute: typeof TrackIdRoute
  TrackIndexRoute: typeof TrackIndexRoute
  ApiExchangeRatesCurrencyRoute: typeof ApiExchangeRatesCurrencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amount': {
      id: '/amount'
      path: '/amount'
      fullPath: '/amount'
      preLoaderRoute: typeof AmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipient': {
      id: '/recipient'
      path: '/recipient'
      fullPath: '/recipient'
      preLoaderRoute: typeof RecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries': {
      id: '/api/countries'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers': {
      id: '/api/transfers'
      path: '/api/transfers'
      fullPath: '/api/transfers'
      preLoaderRoute: typeof ApiTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/$id': {
      id: '/success/$id'
      path: '/success/$id'
      fullPath: '/success/$id'
      preLoaderRoute: typeof SuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rates/$currency': {
      id: '/api/exchange-rates/$currency'
      path: '/api/exchange-rates/$currency'
      fullPath: '/api/exchange-rates/$currency'
      preLoaderRoute: typeof ApiExchangeRatesCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers/$id': {
      id: '/api/transfers/$id'
      path: '/$id'
      fullPath: '/api/transfers/$id'
      preLoaderRoute: typeof ApiTransfersIdRouteImport
      parentRoute: typeof ApiTransfersRoute
    }
    '/api/transfers/$id/status': {
      id: '/api/transfers/$id/status'
      path: '/status'
      fullPath: '/api/transfers/$id/status'
      preLoaderRoute: typeof ApiTransfersIdStatusRouteImport
      parentRoute: typeof ApiTransfersIdRoute
    }
  }
}

interface ApiTransfersIdRouteChildren {
  ApiTransfersIdStatusRoute: typeof ApiTransfersIdStatusRoute
}

const ApiTransfersIdRouteChildren: ApiTransfersIdRouteChildren = {
  ApiTransfersIdStatusRoute: ApiTransfersIdStatusRoute,
}

const ApiTransfersIdRouteWithChildren = ApiTransfersIdRoute._addFileChildren(
  ApiTransfersIdRouteChildren,
)

interface ApiTransfersRouteChildren {
  ApiTransfersIdRoute: typeof ApiTransfersIdRouteWithChildren
}

const ApiTransfersRouteChildren: ApiTransfersRouteChildren = {
  ApiTransfersIdRoute: ApiTransfersIdRouteWithChildren,
}

const ApiTransfersRouteWithChildren = ApiTransfersRoute._addFileChildren(
  ApiTransfersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmountRoute: AmountRoute,
  RecipientRoute: RecipientRoute,
  ReviewRoute: ReviewRoute,
  SendRoute: SendRoute,
  ApiCountriesRoute: ApiCountriesRoute,
  ApiTransfersRoute: ApiTransfersRouteWithChildren,
  SuccessIdRoute: SuccessIdRoute,
  TrackIdRoute: TrackIdRoute,
  TrackIndexRoute: TrackIndexRoute,
  ApiExchangeRatesCurrencyRoute: ApiExchangeRatesCurrencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
